services:
  - type: web
    name: trash-collection-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: PORT
        fromService:
          type: web
          name: trash-collection-app
          property: port 