#!/usr/bin/env python3
"""
Test video detection buttons functionality
"""

import pytest
import json
from unittest.mock import Mock, patch, MagicMock
import tempfile
import os

class TestVideoDetectionButtons:
    """Test the new video detection buttons functionality"""
    
    def test_discard_detection_button_present(self):
        """Test that discard detection button is present in video report"""
        # Mock video detection data
        detection_data = {
            "detection_id": "test-123",
            "total_objects": 5,
            "estimated_weight_kg": 0.8,
            "category_counts": {
                "beverage_containers": 3,
                "food_packaging": 2
            },
            "processing_time": 2.5,
            "timestamp": "2025-01-08T15:34:37.141404",
            "video_info": {
                "original_filename": "test_video.mp4",
                "file_size_mb": 1.2,
                "total_frames_processed": 10
            }
        }
        
        # This would be generated by the frontend JavaScript
        expected_buttons = [
            'discard-detection-btn',
            'rerun-detection-btn',
            'edit-video-report-btn',
            'submit-video-report-btn'
        ]
        
        # Check that all expected buttons are present
        for button_id in expected_buttons:
            assert button_id in self._get_button_ids_from_report(detection_data)
    
    def test_rerun_detection_button_present(self):
        """Test that rerun detection button is present in video report"""
        detection_data = {
            "detection_id": "test-456",
            "total_objects": 3,
            "estimated_weight_kg": 0.5,
            "category_counts": {
                "plastic_items": 2,
                "paper_products": 1
            }
        }
        
        button_ids = self._get_button_ids_from_report(detection_data)
        assert 'rerun-detection-btn' in button_ids
    
    def test_discard_detection_functionality(self):
        """Test discard detection functionality"""
        # Mock current video detection state
        current_detection = {
            'data': {
                'detection_id': 'test-123',
                'total_objects': 5
            },
            'file': Mock()
        }
        
        # Test discard functionality
        result = self._simulate_discard_detection(current_detection)
        
        assert result['status'] == 'success'
        assert result['message'] == 'Video detection discarded. You can upload a new video.'
        assert result['cleared'] == True
    
    def test_rerun_detection_functionality(self):
        """Test rerun detection functionality"""
        # Mock video file and location
        video_file = Mock()
        video_file.name = 'test_video.mp4'
        
        location_data = {
            'latitude': '40.7128',
            'longitude': '-74.0060'
        }
        
        # Test rerun functionality
        result = self._simulate_rerun_detection(video_file, location_data)
        
        assert result['status'] == 'success'
        assert result['detection_id'] is not None
        assert result['category_counts'] is not None
    
    def test_loading_state_during_detection(self):
        """Test that loading state is properly shown during detection"""
        # Test loading state
        loading_state = self._simulate_loading_state(True)
        
        assert loading_state['is_loading'] == True
        assert loading_state['button_disabled'] == True
        assert 'Detecting Trash...' in loading_state['button_text']
        assert 'animate-spin' in loading_state['spinner_class']
    
    def test_loading_state_after_detection(self):
        """Test that loading state is properly reset after detection"""
        # Test normal state
        normal_state = self._simulate_loading_state(False)
        
        assert normal_state['is_loading'] == False
        assert normal_state['button_disabled'] == False
        assert 'Detect Trash' in normal_state['button_text']
        assert 'hidden' in normal_state['spinner_class']
    
    def test_button_styling(self):
        """Test that buttons have correct styling"""
        button_styles = {
            'discard-detection-btn': {
                'text_color': 'text-red-700',
                'bg_color': 'bg-red-100',
                'border_color': 'border-red-300',
                'icon': 'bi-trash'
            },
            'rerun-detection-btn': {
                'text_color': 'text-orange-700',
                'bg_color': 'bg-orange-100',
                'border_color': 'border-orange-300',
                'icon': 'bi-arrow-clockwise'
            }
        }
        
        for button_id, expected_styles in button_styles.items():
            styles = self._get_button_styles(button_id)
            assert styles['text_color'] == expected_styles['text_color']
            assert styles['bg_color'] == expected_styles['bg_color']
            assert styles['border_color'] == expected_styles['border_color']
            assert expected_styles['icon'] in styles['icon_class']
    
    def test_button_visibility_logic(self):
        """Test that buttons are only visible when appropriate"""
        # Test initial state (no detection)
        initial_state = self._get_button_visibility_state({})
        assert initial_state['discard_visible'] == False
        assert initial_state['rerun_visible'] == False
        assert initial_state['submit_visible'] == False
        
        # Test after detection
        detection_state = self._get_button_visibility_state({
            'detection_id': 'test-123',
            'total_objects': 5
        })
        assert detection_state['discard_visible'] == True
        assert detection_state['rerun_visible'] == True
        assert detection_state['submit_visible'] == True
    
    def test_discard_clears_detection_and_video(self):
        """Test that discard detection clears both detection and video file"""
        # Simulate state before discard
        current_detection = {'data': {'detection_id': 'test-123'}, 'file': Mock()}
        currentDetectionData = {'detection_id': 'test-123'}
        currentVideoFile = Mock()
        # Simulate discard
        result = self._simulate_discard_detection_and_video(currentDetectionData, currentVideoFile)
        assert result['detection'] is None
        assert result['video'] is None
        assert result['status'] == 'success'

    def test_rerun_not_possible_after_discard(self):
        """Test that rerun detection is not possible after discard until a new video is uploaded"""
        # Simulate state after discard
        currentDetectionData = None
        currentVideoFile = None
        # Try rerun
        result = self._simulate_rerun_detection(currentVideoFile, {'latitude': '1', 'longitude': '2'})
        assert result['status'] == 'error'
        assert 'No video file' in result['message']

    # Helper methods for testing
    def _get_button_ids_from_report(self, detection_data):
        """Simulate getting button IDs from generated report HTML"""
        # This would normally be done by parsing the HTML generated by generateVideoReportContent
        return [
            'discard-detection-btn',
            'rerun-detection-btn', 
            'edit-video-report-btn',
            'submit-video-report-btn'
        ]
    
    def _simulate_discard_detection(self, current_detection):
        """Simulate discard detection functionality"""
        if not current_detection:
            return {'status': 'error', 'message': 'No video detection to discard.'}
        
        # Simulate clearing the detection
        return {
            'status': 'success',
            'message': 'Video detection discarded. You can upload a new video.',
            'cleared': True
        }
    
    def _simulate_rerun_detection(self, video_file, location_data):
        """Simulate rerun detection functionality"""
        if not video_file:
            return {'status': 'error', 'message': 'No video file available to rerun detection. Please upload a video.'}
        if not location_data.get('latitude') or not location_data.get('longitude'):
            return {'status': 'error', 'message': 'Missing required data for rerun.'}
        # Simulate successful rerun
        return {
            'status': 'success',
            'detection_id': 'rerun-test-456',
            'category_counts': {
                'beverage_containers': 4,
                'food_packaging': 1
            },
            'total_objects': 5,
            'estimated_weight_kg': 0.9
        }
    
    def _simulate_loading_state(self, is_loading):
        """Simulate loading state for detect button"""
        if is_loading:
            return {
                'is_loading': True,
                'button_disabled': True,
                'button_text': 'Detecting Trash...',
                'spinner_class': 'animate-spin'
            }
        else:
            return {
                'is_loading': False,
                'button_disabled': False,
                'button_text': 'Detect Trash',
                'spinner_class': 'hidden'
            }
    
    def _get_button_styles(self, button_id):
        """Get button styles for testing"""
        styles = {
            'discard-detection-btn': {
                'text_color': 'text-red-700',
                'bg_color': 'bg-red-100',
                'border_color': 'border-red-300',
                'icon_class': 'bi bi-trash mr-1'
            },
            'rerun-detection-btn': {
                'text_color': 'text-orange-700',
                'bg_color': 'bg-orange-100',
                'border_color': 'border-orange-300',
                'icon_class': 'bi bi-arrow-clockwise mr-1'
            }
        }
        return styles.get(button_id, {})
    
    def _get_button_visibility_state(self, detection_data):
        """Get button visibility state based on detection data"""
        has_detection = bool(detection_data.get('detection_id'))
        
        return {
            'discard_visible': has_detection,
            'rerun_visible': has_detection,
            'submit_visible': has_detection
        }

    def _simulate_discard_detection_and_video(self, detection, video):
        # Simulate the discard logic
        detection = None
        video = None
        return {'detection': detection, 'video': video, 'status': 'success'}

if __name__ == "__main__":
    # Run tests
    test_instance = TestVideoDetectionButtons()
    
    print("Running video detection buttons tests...")
    
    # Test button presence
    test_instance.test_discard_detection_button_present()
    test_instance.test_rerun_detection_button_present()
    
    # Test functionality
    test_instance.test_discard_detection_functionality()
    test_instance.test_rerun_detection_functionality()
    
    # Test loading states
    test_instance.test_loading_state_during_detection()
    test_instance.test_loading_state_after_detection()
    
    # Test styling
    test_instance.test_button_styling()
    
    # Test visibility logic
    test_instance.test_button_visibility_logic()
    
    # Test discard and rerun after discard
    test_instance.test_discard_clears_detection_and_video()
    test_instance.test_rerun_not_possible_after_discard()
    
    print("✓ All video detection buttons tests passed!") 